###############
# Author info #
###############

author:
    # Site's author name
    # Default: not set (author name is not displayed)
    name: Your awesome name

    # Site's author email
    # Default: not set (author email is not displayed)
    email: your-email@yourdomain.com

############
# Building #
############

# Encoding
# Set the encoding of files by name
# Default: "utf-8"
# encoding: "utf-8"

# Available encodings can be shown by the command:
# ruby -e 'puts Encoding::list.join("\n")'

# Excerpt separator
# Completely disable excerpts by setting your excerpt_separator to ""
# Default: "\n\n"
# excerpt_separator: "\n\n"

# For more info on post excerpts, please refer to
# http://jekyllrb.com/docs/posts/#post-excerpts

# Markdown renderer
# Sets the Markdown renderer to be used by Jekyll (kramdown, redcarpet or your
# own)
# Default: kramdown
# markdown: kramdown

# For more info on how to use and configure Markdown renderers, as well as how
# to create custom renderers, please refer to
# http://jekyllrb.com/docs/configuration/#markdown-options

##############
# Pagination #
##############

# Specifies how many items should be displayed per page
# Default: not set (pagination disabled)
# paginate: 10

# You may also specify the destination of the pagination pages
# Default: /page:num (for example, /page2, /page3, etc)
# paginate_path: "/blog/page/:num/"

# For more info on pagination, please refer to
# http://jekyllrb.com/docs/pagination/

##############
# Publishing #
##############

# Site URL
# The base protocol and hostname for the website
# Default: not set (this variable is only necessary for external systems)
# url: "http://yourdomain.com"

###########
# Serving #
###########

# Base URL
# Serve the website from the given base URL (does not include hostname)
# Default: "" (website is at the root of the domain)
# baseurl: ""

# For more info on the serve command options, please refer to
# http://jekyllrb.com/docs/configuration/

#################
# Site settings #
#################

# Site title
title: Your awesome title

# Site description
description: > # this means to ignore newlines until the text ends
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.

# Site language
# A language tag following the language tag syntax (IETF's BCP 47). This is
# meant to assist search engines and browsers.
# Default: not set (do not associate any language with this site's content)
lang: en

# For more info on language tags, please refer to
# http://www.w3.org/International/articles/language-tags/

###################
# Social networks #
###################

# GitHub username
# Example: jekyll, if your GitHub URL is https://github.com/jekyll
# Default: not set (GitHub URL is not displayed)
github_username:  jekyll

# Twitter username
# Example: jekyllrb, if your Twitter URL is https://twitter.com/jekyllrb
# Default: not set (Twitter URL is not displayed)
twitter_username: jekyllrb
